### ISSUE TITLE
chores

### ISSUE THREAD

**Issue by aiyeola** [CodeLeom/bank_API#1]
Hi, I believe this project will grow and a lot of people will come to contribute, would you be kind to let me set up this project to conform to code format standards, commit lint standards, es6, a build system. What do you think?

**Comment by CodeLeom** [comment]
Ok, great. You can go ahead

**Comment by aiyeola** [comment]
code format, I recommend airbnb

**Comment by aiyeola** [comment]
Alright, I'll make a PR implementing this soonest. Thanks
